### ISSUE TITLE
Slight issue with timing after cert-manager installed

### ISSUE THREAD

**Issue by jurlwin** [ChrisThePCGeek/k3s-ansible-traefik-rancher#4]
Hey Chris -- I ended up increasing the sleep time for a RPI cluster install to separate the cert-manager before longhorn.

 - name: wait 15s for cert-manager to fully deploy
   wait_for:
-    timeout: 15
+    timeout: 60

- but -- there may be a more painful, but better way.  The cert manager installation has me get cmctl and check that way
e.g. 
OS=$(go env GOOS); ARCH=$(go env GOARCH); curl -sSL -o cmctl.tar.gz https://github.com/cert-manager/cert-manager/releases/download/v1.7.2/cmctl-$OS-$ARCH.tar.gz\ntar xzf cmctl.tar.gz\nsudo mv cmctl /usr/local/bin
cmctl check api --wait=2m

I think the installation may have some challenges, given Go and other requirements, but may be a suggestion you consider.

IF you want some help implementing/testing, be happy to do so, but...either way, just noting that my cert-manager needed a bit more time.  I just tagged it at 60.  It could only need 15... :)

**Comment by ChrisThePCGeek** [comment]
Oh okay thank you!  I think there is a way to check it with a helm command or have the command not return until the deployment finishes that way the next step has to wait.  I will look into that though. I knew I needed a slight delay but never re-visited doing it more properly.

**Comment by jurlwin** [comment]
if there is a helm command, that would be great.  The cert-manager docs pointed me that way, and I thought it might be a bit painful, so I put the sleep in :) 

If it were just a binary install/package, it would have been worth it, but go + the download made me “concerned” about the viability.  Sure, I could develop it and put it in Ansible, but i don’t have a good way to test it across all platforms, hence my hesitation...

**Comment by ChrisThePCGeek** [comment]
All set.  I added --wait to the helm command and in my test it waited until cert-manager was completely deployed before continuing with the playbook.

**Comment by jurlwin** [comment]
awesome!  Time to pull another version :)
