### ISSUE TITLE
cmd tasks in ./roles/traefik/tasks/main.yaml are failing

### ISSUE THREAD

**Issue by itsbanjo** [ChrisThePCGeek/k3s-ansible-traefik-rancher#5]
Had to add environment: to force KUBECONFIG on each tasks so it picks up the newly generated kubeconfig.

**Comment by ChrisThePCGeek** [comment]
That may very well be something specific to your config/setup. I've tested it many many times with 0 issues.  Re-tested just now with Debian 12 vm's for nodes and no issues.  All the helm commands are executed on the first master server node in the ansible user's environment which would have already had the kubeconfig file placed under their home path by the prior steps in the playbook.

**Comment by itsbanjo** [comment]
Cheers Chris, are you able to share ansible.cfg? I'll give it a go in my lab.

**Comment by ChrisThePCGeek** [comment]
its part of the repo.  https://github.com/ChrisThePCGeek/k3s-ansible-traefik-rancher/blob/e60eb1e0886b79a06d81fd3d980a7e300f69ca60/ansible.cfg

**Comment by ChrisThePCGeek** [comment]
Super old issue, closing as resolved
